export const CLIENT_SET = 'CLIENT_SET';
export const CLIENT_UNSET = 'CLIENT_UNSET';
export const HOME_BEGIN_DATA_COLLECTION = 'HOME_BEGIN_DATA_COLLECTION';
export const HOME_GET_GEOIPINFO_SUCCESS = 'HOME_GET_GEOIPINFO_SUCCESS';